import type { Metadata } from "next";
import { Cairo } from "next/font/google";
import "./globals.css";
import Footer from "./Section/Footer";
import Navbar from "./Section/Navbar";
import { ThemeProvider } from "@/components/ui/theme-provider";
const cairo = Cairo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body className={`${cairo.className} dark:bg-black  antialiased `}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            <div className=" max-w-screen-xl px-4 md:px-6  py-4 md:py-2  mx-auto ">
              <div className="container mx-auto">{children}</div>
            </div>
            <Footer />
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
